"$schema" = "./node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "pdf-wise"
# Set this to today's date
compatibility_date = "2026-03-22"
compatibility_flags = [ "nodejs_compat", "global_fetch_strictly_public" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"